<a href="https://colab.research.google.com/github/SANTHOSH-C08/AI-INTERNSHIP/blob/main/Eclat_and_FP_Growth.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
df=pd.read_csv("/content/Market_Basket_Optimisation.csv")

In [ ]:
df.head()

,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
0,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.tail()

,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
7495,butter,light mayo,fresh bread,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7496,burgers,frozen vegetables,eggs,french fries,magazines,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7497,chicken,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7498,escalope,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7499,eggs,frozen smoothie,yogurt cake,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7500 entries, 0 to 7499
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   shrimp             7500 non-null   object
 1   almonds            5746 non-null   object
 2   avocado            4388 non-null   object
 3   vegetables mix     3344 non-null   object
 4   green grapes       2528 non-null   object
 5   whole weat flour   1863 non-null   object
 6   yams               1368 non-null   object
 7   cottage cheese     980 non-null    object
 8   energy drink       653 non-null    object
 9   tomato juice       394 non-null    object
 10  low fat yogurt     255 non-null    object
 11  green tea          153 non-null    object
 12  honey              86 non-null     object
 13  salad              46 non-null     object
 14  mineral water      24 non-null     object
 15  salmon             7 non-null      object
 16  antioxydant juice  3 non-null      object
 17  frozen smoothie    3 non-null      object
 18  spinach            2 non-null      object
 19  olive oil          0 non-null      float64
dtypes: float64(1), object(19)
memory usage: 1.1+ MB

In [ ]:
df.isnull().sum()

shrimp                  0
almonds              1754
avocado              3112
vegetables mix       4156
green grapes         4972
whole weat flour     5637
yams                 6132
cottage cheese       6520
energy drink         6847
tomato juice         7106
low fat yogurt       7245
green tea            7347
honey                7414
salad                7454
mineral water        7476
salmon               7493
antioxydant juice    7497
frozen smoothie      7497
spinach              7498
olive oil            7500
dtype: int64

In [ ]:
transaction=[]
for i in range(0,len(df)):
  transaction.append([str(df.values[i,j])for j in range(0,20)if str(df.values[i,j])!='nan'])

In [ ]:
transaction

[['burgers', 'meatballs', 'eggs'],
 ['chutney'],
 ['turkey', 'avocado'],
 ['mineral water', 'milk', 'energy bar', 'whole wheat rice', 'green tea'],
 ['low fat yogurt'],
 ['whole wheat pasta', 'french fries'],
 ['soup', 'light cream', 'shallot'],
 ['frozen vegetables', 'spaghetti', 'green tea'],
 ['french fries'],
 ['eggs', 'pet food'],
 ['cookies'],
 ['turkey', 'burgers', 'mineral water', 'eggs', 'cooking oil'],
 ['spaghetti', 'champagne', 'cookies'],
 ['mineral water', 'salmon'],
 ['mineral water'],
 ['shrimp',
  'chocolate',
  'chicken',
  'honey',
  'oil',
  'cooking oil',
  'low fat yogurt'],
 ['turkey', 'eggs'],
 ['turkey',
  'fresh tuna',
  'tomatoes',
  'spaghetti',
  'mineral water',
  'black tea',
  'salmon',
  'eggs',
  'chicken',
  'extra dark chocolate'],
 ['meatballs', 'milk', 'honey', 'french fries', 'protein bar'],
 ['red wine', 'shrimp', 'pasta', 'pepper', 'eggs', 'chocolate', 'shampoo'],
 ['rice', 'sparkling water'],
 ['spaghetti', 'mineral water', 'ham', 'body spray', 'pancakes', 'green tea'],
 ['burgers',
  'grated cheese',
  'shrimp',
  'pasta',
  'avocado',
  'honey',
  'white wine',
  'toothpaste'],
 ['eggs'],
 ['parmesan cheese', 'spaghetti', 'soup', 'avocado', 'milk', 'fresh bread'],
 ['ground beef',
  'spaghetti',
  'mineral water',
  'milk',
  'energy bar',
  'black tea',
  'salmon',
  'frozen smoothie',
  'escalope'],
 ['sparkling water'],
 ['mineral water', 'eggs', 'chicken', 'chocolate', 'french fries'],
 ['frozen vegetables', 'spaghetti', 'yams', 'mineral water'],
 ['herb & pepper', 'tomato sauce', 'light cream', 'magazines'],
 ['mineral water', 'chocolate', 'avocado', 'eggs'],
 ['turkey', 'french fries', 'strawberries'],
 ['frozen vegetables', 'strong cheese', 'chocolate'],
 ['cookies'],
 ['pickles', 'spaghetti', 'salmon', 'escalope'],
 ['energy bar', 'french fries'],
 ['red wine', 'ground beef', 'mineral water'],
 ['mineral water', 'cake', 'cottage cheese'],
 ['pickles', 'champagne', 'green tea'],
 ['spaghetti'],
 ['fresh tuna',
  'frozen vegetables',
  'spaghetti',
  'mineral water',
  'honey',
  'whole wheat rice',
  'frozen smoothie',
  'escalope'],
 ['spaghetti'],
 ['soup', 'meatballs', 'hot dogs', 'sparkling water'],
 ['escalope'],
 ['soup',
  'avocado',
  'french fries',
  'hot dogs',
  'brownies',
  'body spray',
  'pancakes',
  'green tea'],
 ['mineral water', 'chicken', 'cereals', 'clothes accessories'],
 ['mineral water', 'bug spray'],
 ['avocado', 'muffins'],
 ['burgers', 'black tea', 'green tea'],
 ['spaghetti', 'chocolate', 'brownies', 'white wine', 'green tea'],
 ['fresh tuna', 'mineral water', 'eggs'],
 ['spaghetti', 'muffins'],
 ['spaghetti', 'chocolate'],
 ['french fries', 'escalope', 'champagne'],
 ['tomato sauce', 'light mayo'],
 ['turkey',
  'fresh tuna',
  'frozen vegetables',
  'tomatoes',
  'ground beef',
  'spaghetti',
  'mineral water',
  'chocolate',
  'soup',
  'milk',
  'olive oil'],
 ['eggs', 'cookies'],
 ['soup',
  'chicken',
  'gums',
  'soda',
  'body spray',
  'energy drink',
  'green tea'],
 ['turkey',
  'frozen vegetables',
  'mineral water',
  'cider',
  'cooking oil',
  'green tea'],
 ['spaghetti'],
 ['clothes accessories'],
 ['energy drink'],
 ['soup', 'bug spray', 'shallot', 'protein bar', 'green tea'],
 ['turkey', 'eggs'],
 ['french fries'],
 ['chocolate', 'milk'],
 ['herb & pepper',
  'whole wheat pasta',
  'ground beef',
  'mineral water',
  'avocado',
  'cider',
  'whole wheat rice'],
 ['cookies'],
 ['shrimp', 'pasta'],
 ['grated cheese', 'herb & pepper', 'tomatoes', 'tomato sauce', 'corn'],
 ['burgers', 'escalope', 'shallot'],
 ['cookies'],
 ['yogurt cake'],
 ['soup', 'eggs'],
 ['cookies'],
 ['mineral water', 'chocolate', 'low fat yogurt'],
 ['eggs', 'strawberries'],
 ['grated cheese', 'ground beef', 'spaghetti', 'mineral water', 'white wine'],
 ['mint'],
 ['eggs', 'cake', 'french fries'],
 ['burgers', 'spaghetti', 'milk', 'french fries', 'green tea'],
 ['mineral water', 'energy bar', 'butter', 'french fries'],
 ['burgers',
  'grated cheese',
  'herb & pepper',
  'mineral water',
  'eggs',
  'cooking oil'],
 ['energy bar'],
 ['energy bar', 'energy drink'],
 ['chocolate', 'frozen smoothie'],
 ['low fat yogurt'],
 ['asparagus', 'salad'],
 ['burgers', 'french fries', 'low fat yogurt', 'green tea'],
 ['low fat yogurt'],
 ['burgers',
  'herb & pepper',
  'shrimp',
  'pasta',
  'spaghetti',
  'mineral water',
  'meatballs',
  'olive oil',
  'energy bar',
  'french wine',
  'eggs',
  'salt'],
 ['champagne', 'low fat yogurt'],
 ['champagne'],
 ['burgers', 'almonds', 'eggs', 'french fries', 'cookies', 'green tea'],
 ['ham', 'soup', 'escalope', 'body spray'],
 ['turkey',
  'ham',
  'frozen vegetables',
  'pepper',
  'oil',
  'extra dark chocolate',
  'tea',
  'magazines'],
 ['muffins', 'eggs', 'cookies'],
 ['cookies'],
 ['frozen vegetables',
  'whole wheat pasta',
  'ground beef',
  'spaghetti',
  'chocolate',
  'green tea'],
 ['mineral water', 'barbecue sauce', 'chocolate'],
 ['burgers',
  'herb & pepper',
  'energy bar',
  'almonds',
  'eggs',
  'corn',
  'mayonnaise',
  'zucchini'],
 ['turkey',
  'burgers',
  'ground beef',
  'chocolate',
  'soup',
  'almonds',
  'eggs',
  'hot dogs',
  'cottage cheese'],
 ['ham', 'spaghetti', 'chocolate', 'eggs'],
 ['ground beef', 'energy bar', 'pet food', 'carrots', 'protein bar'],
 ['ground beef',
  'tomato sauce',
  'spaghetti',
  'mineral water',
  'almonds',
  'eggs'],
 ['mineral water', 'olive oil', 'gums', 'cooking oil'],
 ['shrimp',
  'pasta',
  'mineral water',
  'soup',
  'avocado',
  'milk',
  'olive oil',
  'green grapes',
  'eggs',
  'bug spray'],
 ['shrimp',
  'pasta',
  'soup',
  'cake',
  'cooking oil',
  'chicken',
  'light mayo',
  'low fat yogurt'],
 ['spaghetti',
  'mineral water',
  'chocolate',
  'french fries',
  'champagne',
  'escalope',
  'mushroom cream sauce',
  'fresh bread'],
 ['shrimp', 'pasta', 'mineral water', 'eggs'],
 ['burgers', 'oil', 'tomato juice', 'fresh bread'],
 ['french wine', 'eggs', 'chocolate', 'low fat yogurt'],
 ['chicken', 'eggs', 'french fries', 'pancakes'],
 ['turkey', 'herb & pepper', 'salmon', 'white wine', 'candy bars'],
 ['grated cheese',
  'spaghetti',
  'olive oil',
  'eggs',
  'french fries',
  'green tea'],
 ['mineral water', 'energy bar'],
 ['eggs', 'french fries'],
 ['burgers',
  'tomatoes',
  'mineral water',
  'soup',
  'milk',
  'almonds',
  'eggs',
  'chocolate',
  'tomato juice'],
 ['muffins'],
 ['pasta'],
 ['tomatoes', 'spaghetti', 'frozen smoothie'],
 ['ground beef', 'spaghetti', 'milk'],
 ['french fries'],
 ['chocolate', 'milk'],
 ['burgers',
  'shrimp',
  'pasta',
  'frozen vegetables',
  'spaghetti',
  'mineral water',
  'milk',
  'eggs',
  'chocolate',
  'french fries',
  'pancakes',
  'low fat yogurt'],
 ['ground beef', 'mineral water', 'antioxydant juice', 'protein bar'],
 ['grated cheese',
  'whole wheat pasta',
  'ground beef',
  'spaghetti',
  'cake',
  'energy drink'],
 ['grated cheese'],
 ['pancakes'],
 ['frozen smoothie'],
 ['carrots', 'green tea'],
 ['chocolate'],
 ['turkey',
  'burgers',
  'chocolate',
  'olive oil',
  'eggs',
  'cooking oil',
  'corn'],
 ['frozen vegetables',
  'tomatoes',
  'pepper',
  'spaghetti',
  'mineral water',
  'pancakes',
  'chicken',
  'chili',
  'tea',
  'french fries',
  'tomato juice',
  'fresh bread'],
 ['cookies'],
 ['ground beef'],
 ['turkey', 'eggs', 'chocolate', 'frozen smoothie', 'tomato juice'],
 ['frozen vegetables', 'cooking oil', 'mashed potato'],
 ['frozen vegetables',
  'ground beef',
  'tomato sauce',
  'mineral water',
  'meatballs',
  'olive oil',
  'light cream',
  'tomato juice'],
 ['red wine',
  'spaghetti',
  'mineral water',
  'soup',
  'milk',
  'eggs',
  'cake',
  'gums',
  'cooking oil',
  'chocolate',
  'frozen smoothie'],
 ['chocolate',
  'tomatoes',
  'spaghetti',
  'mineral water',
  'avocado',
  'milk',
  'olive oil',
  'eggs',
  'rice',
  'french fries',
  'brownies'],
 ['chocolate',
  'shrimp',
  'pasta',
  'frozen vegetables',
  'ground beef',
  'mineral water',
  'nonfat milk',
  'eggs'],
 ['turkey',
  'shrimp',
  'pasta',
  'pepper',
  'spaghetti',
  'mineral water',
  'eggs',
  'chicken',
  'french fries'],
 ['cookies'],
 ['turkey', 'tomatoes', 'cake'],
 ['yams',
  'mineral water',
  'soup',
  'milk',
  'pancakes',
  'whole wheat rice',
  'barbecue sauce',
  'carrots',
  'chocolate',
  'champagne'],
 ['rice'],
 ['chocolate', 'milk'],
 ['shrimp', 'pasta', 'frozen vegetables', 'water spray'],
 ['burgers', 'mineral water', 'milk', 'eggs', 'whole wheat rice', 'mint'],
 ['mineral water', 'vegetables mix', 'cake', 'frozen smoothie', 'brownies'],
 ['cookies'],
 ['shrimp', 'pasta', 'chicken', 'chocolate bread'],
 ['shallot'],
 ['shrimp', 'pasta', 'spaghetti', 'eggs', 'hot dogs', 'green tea'],
 ['burgers'],
 ['red wine',
  'ground beef',
  'spaghetti',
  'mineral water',
  'milk',
  'olive oil',
  'strong cheese',
  'light cream',
  'cooking oil'],
 ['burgers',
  'grated cheese',
  'spaghetti',
  'avocado',
  'milk',
  'oil',
  'french fries'],
 ['herb & pepper',
  'whole wheat pasta',
  'ground beef',
  'mineral water',
  'olive oil'],
 ['shrimp', 'pasta', 'yams', 'milk', 'chocolate'],
 ['butter', 'green tea'],
 ['light mayo'],
 ['low fat yogurt'],
 ['herb & pepper', 'shrimp', 'pasta', 'spaghetti', 'milk'],
 ['burgers', 'eggs'],
 ['turkey',
  'herb & pepper',
  'ground beef',
  'soup',
  'avocado',
  'milk',
  'black tea',
  'eggs',
  'barbecue sauce',
  'carrots',
  'cookies',
  'tomato juice',
  'fresh bread'],
 ['cookies'],
 ['escalope'],
 ['pepper', 'french fries', 'strawberries', 'pancakes', 'low fat yogurt'],
 ['frozen vegetables', 'yams', 'chicken', 'honey', 'light mayo'],
 ['chocolate', 'champagne'],
 ['herb & pepper', 'honey', 'cake', 'rice', 'protein bar'],
 ['burgers',
  'chocolate',
  'frozen vegetables',
  'ground beef',
  'mineral water',
  'milk',
  'light mayo',
  'asparagus'],
 ['chocolate', 'mineral water', 'corn', 'cottage cheese', 'green tea'],
 ['muffins'],
 ['ham', 'french wine', 'escalope'],
 ['spaghetti', 'milk', 'whole wheat rice', 'mint green tea'],
 ['chocolate', 'body spray'],
 ['frozen vegetables', 'french fries', 'hot dogs'],
 ['candy bars'],
 ['burgers',
  'shrimp',
  'pasta',
  'milk',
  'green tea',
  'french fries',
  'cookies',
  'white wine'],
 ['parmesan cheese', 'ground beef'],
 ['pancakes', 'whole wheat rice', 'candy bars'],
 ['eggs', 'eggplant', 'cookies'],
 ['frozen vegetables', 'mineral water'],
 ['chocolate'],
 ['turkey', 'spaghetti', 'milk', 'whole wheat rice', 'chocolate'],
 ['whole wheat pasta',
  'ground beef',
  'spaghetti',
  'soup',
  'meatballs',
  'chicken',
  'blueberries',
  'cooking oil',
  'champagne',
  'yogurt cake',
  'protein bar'],
 ['cooking oil', 'tomato juice'],
 ['frozen vegetables', 'milk', 'eggs', 'french fries', 'green tea'],
 ['fresh tuna',
  'spaghetti',
  'olive oil',
  'french wine',
  'eggs',
  'french fries',
  'champagne',
  'pancakes',
  'light mayo'],
 ['red wine', 'honey', 'hot dogs'],
 ['milk', 'bacon', 'eggs', 'french fries', 'fresh bread'],
 ['french fries', 'yogurt cake'],
 ['milk'],
 ['french fries'],
 ['chocolate'],
 ['burgers', 'ham', 'red wine'],
 ['shrimp',
  'pasta',
  'tomatoes',
  'energy bar',
  'french wine',
  'antioxydant juice',
  'french fries',
  'frozen smoothie',
  'brownies'],
 ['green tea'],
 ['low fat yogurt'],
 ['turkey',
  'spaghetti',
  'mineral water',
  'soup',
  'spinach',
  'soda',
  'energy drink',
  'salt'],
 ['turkey', 'eggs'],
 ['bug spray', 'hot dogs'],
 ['oil'],
 ['soup',
  'energy bar',
  'chicken',
  'eggs',
  'cake',
  'french fries',
  'body spray',
  'strawberries'],
 ['spaghetti', 'chocolate', 'yogurt cake'],
 ['turkey', 'mineral water', 'meatballs'],
 ['ground beef',
  'mineral water',
  'chocolate',
  'fromage blanc',
  'bacon',
  'hot dogs'],
 ['frozen vegetables', 'mineral water', 'vegetables mix', 'escalope'],
 ['herb & pepper', 'red wine', 'tomatoes'],
 ['whole wheat pasta', 'olive oil', 'cereals', 'brownies', 'green tea'],
 ['cookies'],
 ['olive oil', 'cookies', 'mushroom cream sauce'],
 ['ground beef', 'pancakes', 'cooking oil', 'gluten free bar', 'light mayo'],
 ['mineral water', 'french fries'],
 ['herb & pepper'],
 ['salmon'],
 ['eggs', 'escalope'],
 ['mineral water', 'tomato juice'],
 ['mineral water'],
 ['shrimp', 'mineral water', 'soup', 'black tea'],
 ['cake', 'frozen smoothie'],
 ['turkey',
  'burgers',
  'grated cheese',
  'tomatoes',
  'chocolate',
  'fromage blanc',
  'honey',
  'whole wheat rice'],
 ['frozen vegetables',
  'ground beef',
  'mineral water',
  'olive oil',
  'pancakes'],
 ['turkey',
  'burgers',
  'ground beef',
  'milk',
  'olive oil',
  'cake',
  'fresh bread'],
 ['whole wheat pasta',
  'ground beef',
  'spaghetti',
  'yams',
  'mineral water',
  'soup',
  'chutney',
  'cereals',
  'energy drink',
  'protein bar'],
 ['eggs', 'whole wheat rice', 'cake', 'green tea', 'escalope'],
 ['ground beef', 'yams', 'soup', 'avocado', 'salmon', 'green tea'],
 ['milk'],
 ['spaghetti', 'chocolate'],
 ['whole wheat pasta', 'honey'],
 ['whole wheat pasta', 'green tea'],
 ['spaghetti', 'meatballs', 'vegetables mix', 'chocolate'],
 ['eggs', 'low fat yogurt'],
 ['fresh tuna',
  'shrimp',
  'pasta',
  'mineral water',
  'olive oil',
  'eggs',
  'cake',
  'brownies',
  'tomato juice'],
 ['mineral water', 'green grapes', 'hot dogs', 'fresh bread'],
 ['frozen vegetables', 'meatballs', 'eggs', 'chocolate'],
 ['chocolate'],
 ['meatballs', 'milk'],
 ['low fat yogurt'],
 ['green tea'],
 ['escalope', 'pasta'],
 ['pepper',
  'chocolate',
  'olive oil',
  'french wine',
  'salmon',
  'rice',
  'light mayo',
  'fresh bread',
  'magazines'],
 ['red wine',
  'french wine',
  'vegetables mix',
  'rice',
  'clothes accessories',
  'hot dogs',
  'green tea'],
 ['burgers',
  'dessert wine',
  'spaghetti',
  'chicken',
  'cake',
  'protein bar',
  'green tea'],
 ['french wine', 'cake', 'fresh bread'],
 ['burgers', 'frozen vegetables', 'flax seed', 'eggs'],
 ['red wine'],
 ['pepper', 'mineral water', 'energy bar', 'green grapes'],
 ['milk', 'eggs', 'cake', 'chocolate', 'french fries', 'green tea'],
 ['french fries'],
 ['almonds'],
 ['burgers', 'mineral water', 'green tea'],
 ['milk', 'pancakes'],
 ['pancakes', 'eggs', 'salt', 'tomato juice'],
 ['mineral water'],
 ['ham', 'spaghetti', 'mineral water', 'olive oil'],
 ['salt', 'tomato juice', 'fresh bread'],
 ['spaghetti', 'mushroom cream sauce'],
 ['spaghetti', 'mineral water', 'eggs', 'pet food'],
 ['frozen vegetables', 'spaghetti'],
 ['energy drink'],
 ['muffins'],
 ['turkey', 'milk'],
 ['cookies'],
 ['chocolate'],
 ['spaghetti',
  'mineral water',
  'eggs',
  'cooking oil',
  'chocolate',
  'escalope'],
 ['shrimp', 'frozen vegetables', 'pepper', 'spaghetti', 'green tea'],
 ['burgers',
  'fresh tuna',
  'red wine',
  'mineral water',
  'french fries',
  'hand protein bar',
  'low fat yogurt'],
 ['pancakes', 'eggs', 'energy drink', 'fresh bread'],
 ['strong cheese',
  'salmon',
  'green tea',
  'french fries',
  'frozen smoothie',
  'hot dogs'],
 ['grated cheese',
  'shrimp',
  'pasta',
  'tomatoes',
  'milk',
  'frozen smoothie',
  'sandwich'],
 ['herb & pepper', 'whole wheat pasta', 'olive oil', 'pancakes', 'eggs'],
 ['spaghetti', 'antioxydant juice'],
 ['chocolate', 'milk', 'almonds', 'eggs', 'strawberries', 'white wine'],
 ['french fries', 'strawberries'],
 ['mineral water'],
 ['eggs'],
 ['escalope'],
 ['cake'],
 ['whole wheat pasta', 'antioxydant juice', 'body spray', 'green tea'],
 ['mineral water', 'oil', 'frozen smoothie'],
 ['french fries', 'champagne'],
 ['chocolate', 'french fries'],
 ['frozen vegetables', 'spaghetti', 'eggs'],
 ['hot dogs'],
 ['chocolate', 'cookies'],
 ['pancakes'],
 ['shrimp', 'butter', 'chicken', 'salmon'],
 ['chocolate', 'cookies', 'babies food'],
 ['pepper', 'spaghetti', 'cake', 'chocolate', 'french fries', 'fresh bread'],
 ['avocado', 'oil', 'cereals', 'french fries'],
 ['herb & pepper',
  'spaghetti',
  'mineral water',
  'spinach',
  'eggs',
  'oil',
  'cooking oil',
  'green tea',
  'shampoo',
  'tomato juice',
  'low fat yogurt'],
 ['herb & pepper',
  'frozen vegetables',
  'ground beef',
  'pepper',
  'spaghetti',
  'mint green tea',
  'french fries'],
 ['french fries'],
 ['green tea', 'tomato juice'],
 ['eggs', 'whole wheat rice', 'chocolate'],
 ['grated cheese',
  'herb & pepper',
  'red wine',
  'spaghetti',
  'mineral water',
  'salmon',
  'eggs',
  'cooking oil',
  'green tea'],
 ['french fries',
  'cookies',
  'shallot',
  'tomato juice',
  'fresh bread',
  'low fat yogurt'],
 ['burgers', 'fresh tuna', 'spaghetti', 'muffins', 'honey'],
 ['herb & pepper', 'ground beef', 'spaghetti', 'eggs', 'chicken'],
 ['grated cheese', 'muffins', 'tomato juice', 'mayonnaise'],
 ['whole wheat pasta',
  'yams',
  'mineral water',
  'muffins',
  'frozen smoothie',
  'hot dogs',
  'energy drink'],
 ['burgers',
  'spaghetti',
  'soup',
  'milk',
  'olive oil',
  'salmon',
  'eggs',
  'blueberries'],
 ['chocolate', 'champagne', 'magazines'],
 ['frozen vegetables',
  'spaghetti',
  'yams',
  'mineral water',
  'french wine',
  'green grapes',
  'rice',
  'chocolate'],
 ['tomato sauce', 'chocolate'],
 ['milk', 'eggs'],
 ['pet food'],
 ['yogurt cake'],
 ['green tea'],
 ['escalope', 'pasta'],
 ['herb & pepper', 'ground beef'],
 ['mineral water', 'honey', 'brownies'],
 ['turkey', 'eggs', 'cake', 'energy drink'],
 ['turkey',
  'burgers',
  'dessert wine',
  'ground beef',
  'soup',
  'salmon',
  'eggs',
  'gums',
  'tomato juice',
  'candy bars'],
 ['spaghetti', 'mineral water', 'chicken'],
 ['turkey', 'ground beef', 'carrots', 'french fries', 'melons'],
 ['mineral water', 'eggs', 'low fat yogurt'],
 ['turkey', 'cooking oil', 'shampoo'],
 ['spaghetti', 'hot dogs'],
 ['chocolate', 'green tea'],
 ['grated cheese',
  'pepper',
  'mineral water',
  'chocolate',
  'eggs',
  'cake',
  'mashed potato',
  'tomato juice'],
 ['chocolate'],
 ['spaghetti', 'olive oil', 'strong cheese', 'pancakes'],
 ['red wine', 'mineral water', 'soup', 'rice', 'cookies'],
 ['red wine', 'shrimp', 'spaghetti'],
 ['green tea'],
 ['mineral water', 'chicken', 'french fries', 'frozen smoothie'],
 ['muffins'],
 ['cake', 'chocolate'],
 ['fresh tuna',
  'tomatoes',
  'mineral water',
  'soup',
  'avocado',
  'meatballs',
  'olive oil'],
 ['turkey', 'french fries'],
 ['burgers',
  'turkey',
  'herb & pepper',
  'ground beef',
  'pancakes',
  'eggs',
  'light cream',
  'rice',
  'champagne',
  'fresh bread'],
 ['escalope'],
 ['chocolate', 'escalope', 'fresh bread'],
 ['ham',
  'spaghetti',
  'french wine',
  'vegetables mix',
  'chocolate',
  'french fries'],
 ['avocado', 'light mayo'],
 ['spaghetti', 'yams', 'butter', 'chocolate'],
 ['energy bar', 'eggs', 'french fries'],
 ['fresh tuna', 'barbecue sauce', 'eggplant'],
 ['energy drink'],
 ['whole wheat rice', 'french fries', 'hot dogs', 'green tea'],
 ['mineral water', 'chicken', 'green tea'],
 ['eggs', 'cake', 'mushroom cream sauce'],
 ['escalope'],
 ['antioxydant juice', 'escalope'],
 ['shrimp', 'spaghetti', 'french fries'],
 ['grated cheese', 'spaghetti', 'salmon', 'tomato juice'],
 ['spaghetti', 'green tea'],
 ['champagne', 'protein bar'],
 ['mineral water', 'avocado', 'chocolate'],
 ['tomatoes', 'champagne', 'green tea'],
 ['chicken', 'french fries', 'escalope'],
 ['frozen vegetables',
  'tomatoes',
  'eggs',
  'green tea',
  'frozen smoothie',
  'light mayo'],
 ['ground beef',
  'chicken',
  'cider',
  'green grapes',
  'honey',
  'chocolate',
  'french fries',
  'champagne',
  'frozen smoothie',
  'escalope'],
 ['french fries', 'champagne'],
 ['mineral water', 'soup'],
 ['frozen vegetables', 'spaghetti', 'milk', 'chocolate', 'babies food'],
 ['honey', 'whole wheat rice'],
 ['whole wheat rice', 'chicken', 'tomato juice'],
 ['pancakes'],
 ['green tea', 'protein bar', 'tomato juice', 'candy bars'],
 ['french fries'],
 ['mineral water'],
 ['escalope'],
 ['grated cheese',
  'herb & pepper',
  'whole wheat pasta',
  'yams',
  'mineral water',
  'bacon',
  'nonfat milk',
  'spinach'],
 ['spaghetti', 'milk'],
 ['milk', 'chocolate', 'white wine'],
 ['sandwich'],

In [ ]:
!pip install pyECLAT

Collecting pyECLAT
  Downloading pyECLAT-1.0.2-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: pandas>=0.25.3 in /usr/local/lib/python3.12/dist-packages (from pyECLAT) (2.2.2)
Requirement already satisfied: numpy>=1.17.4 in /usr/local/lib/python3.12/dist-packages (from pyECLAT) (2.0.2)
Requirement already satisfied: tqdm>=4.41.1 in /usr/local/lib/python3.12/dist-packages (from pyECLAT) (4.67.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.25.3->pyECLAT) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.25.3->pyECLAT) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.25.3->pyECLAT) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=0.25.3->pyECLAT) (1.17.0)
Downloading pyECLAT-1.0.2-py3-none-any.whl (6.3 kB)
Installing collected packages: pyECLAT
Successfully installed pyECLAT-1.0.2

In [ ]:
transaction_df = pd.DataFrame(transaction)

In [ ]:
from pyECLAT import ECLAT

eclat_instance = ECLAT(data=transaction_df)

indices, supports = eclat_instance.fit(
      min_support=0.003,
      min_combination=2,
      max_combination=2
  )

Combination 2 by 2

6555it [02:49, 38.60it/s]

In [ ]:
eclat_df = pd.DataFrame({
    'Itemset': list(supports.keys()),
    'Support': list(supports.values())
})

eclat_df

                           Itemset   Support
0                  honey & avocado  0.003067
1                   honey & salmon  0.003333
2                     honey & eggs  0.005733
3                 honey & tomatoes  0.005333
4          honey & frozen smoothie  0.005733
..                             ...       ...
780         whole wheat rice & ham  0.004267
781      whole wheat rice & butter  0.003200
782                chocolate & ham  0.006267
783             chocolate & butter  0.008267
784  chocolate & whole wheat pasta  0.006267

[785 rows x 2 columns]

In [ ]:
eclat_df=eclat_df.sort_values(by='Support',ascending=False)
eclat_df

                         Itemset   Support
258    spaghetti & mineral water  0.059733
693    mineral water & chocolate  0.052667
143         eggs & mineral water  0.050933
688         mineral water & milk  0.048000
687  mineral water & ground beef  0.040933
..                           ...       ...
95         bacon & mineral water  0.003067
695       mineral water & butter  0.003067
427         french fries & pasta  0.003067
405     french fries & meatballs  0.003067
741             burgers & butter  0.003067

[785 rows x 2 columns]

In [ ]:
!pip install mlxtend

Requirement already satisfied: mlxtend in /usr/local/lib/python3.12/dist-packages (0.23.4)
Requirement already satisfied: scipy>=1.2.1 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (1.16.3)
Requirement already satisfied: numpy>=1.16.2 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (2.0.2)
Requirement already satisfied: pandas>=0.24.2 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (2.2.2)
Requirement already satisfied: scikit-learn>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (1.6.1)
Requirement already satisfied: matplotlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (3.10.0)
Requirement already satisfied: joblib>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (1.5.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.2->mlxtend) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.2->mlxtend) (2026.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.3.1->mlxtend) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.17.0)

In [ ]:
from mlxtend.preprocessing import TransactionEncoder

te = TransactionEncoder()
te_array = te.fit(transaction).transform(transaction)

df_encoded = pd.DataFrame(
    te_array,
    columns=te.columns_
)

In [ ]:
from mlxtend.frequent_patterns import fpgrowth, association_rules

# One-hot encoded transaction data
freq_items = fpgrowth(
    df_encoded,
    min_support=0.003,
    use_colnames=True
)
freq_items

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

       support                           itemsets
0     0.179733                             (eggs)
1     0.087200                          (burgers)
2     0.020933                        (meatballs)
3     0.004133                          (chutney)
4     0.062533                           (turkey)
...        ...                                ...
1437  0.004000              (eggs, fromage blanc)
1438  0.003733         (spaghetti, fromage blanc)
1439  0.003067             (green tea, flax seed)
1440  0.003467           (spaghetti, green beans)
1441  0.003333  (mineral water, whole weat flour)

[1442 rows x 2 columns]

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
rules = association_rules(
    freq_items,
    metric="confidence",
    min_threshold=0.3
)

rules = rules[rules['lift'] >= 2]

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
fp_df = pd.DataFrame({
    'LHS': rules['antecedents'].apply(lambda x: ', '.join(list(x))),
    'RHS': rules['consequents'].apply(lambda x: ', '.join(list(x))),
    'Support': rules['support'],
    'Confidence': rules['confidence'],
    'Lift': rules['lift']
})

fp_df

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

                       LHS            RHS   Support  Confidence      Lift
4    burgers, french fries           eggs  0.009067    0.412121  2.292959
8            milk, burgers      spaghetti  0.006400    0.358209  2.057096
14      burgers, chocolate           milk  0.005467    0.320312  2.471547
15      burgers, chocolate      spaghetti  0.006400    0.375000  2.153522
18    burgers, ground beef           milk  0.004133    0.344444  2.657750
..                     ...            ...       ...         ...       ...
660            nonfat milk  mineral water  0.005067    0.487179  2.044682
663            blueberries      spaghetti  0.003467    0.376812  2.163926
666                  bacon      spaghetti  0.003200    0.369231  2.120391
668              flax seed      green tea  0.003067    0.338235  2.562389
669            green beans      spaghetti  0.003467    0.400000  2.297090

[355 rows x 5 columns]

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
fp_df=fp_df.sort_values(by='Lift',ascending=False)
fp_df

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

,LHS,RHS,Support,Confidence,Lift
153,"soup, frozen vegetables","milk, mineral water",0.003067,0.383333,7.986111
128,"whole wheat pasta, mineral water",olive oil,0.003867,0.402778,6.127451
549,"spaghetti, tomato sauce",ground beef,0.003067,0.489362,4.979936
402,pasta,escalope,0.005867,0.372881,4.700185
541,"herb & pepper, french fries",ground beef,0.003200,0.461538,4.696796
...,...,...,...,...,...
324,"french fries, chicken",spaghetti,0.003867,0.349398,2.006495
386,extra dark chocolate,mineral water,0.005733,0.477778,2.005223
588,olive oil,spaghetti,0.022933,0.348884,2.003547
488,"mineral water, escalope",chocolate,0.005600,0.328125,2.002390
573,"cake, pancakes",spaghetti,0.004133,0.348315,2.000275

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)