In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/preprocessing_dataset.csv")

In [11]:
df.info

<bound method DataFrame.info of       Name    Age Gender   Salary Department
0    Alice   25.0      F  50000.0         HR
1      Bob   30.0      M  60000.0    Finance
2  Charlie    NaN      M  55000.0         IT
3    David   40.0      M  58000.0         HR
4      Eve   22.0      F  52000.0         IT
5    Frank   35.0    NaN  61000.0    Finance
6    Grace  120.0      F      NaN    Finance
7    Henry   28.0      M  59000.0         HR
8      Ivy   29.0      F  63000.0         IT
9     Jack   27.0      M  62000.0    Finance>

In [12]:
df.describe()

              Age        Salary
count    9.000000      9.000000
mean    39.555556  57777.777778
std     30.631320   4521.553322
min     22.000000  50000.000000
25%     27.000000  55000.000000
50%     29.000000  59000.000000
75%     35.000000  61000.000000
max    120.000000  63000.000000

In [13]:
df.head()

      Name   Age Gender   Salary Department
0    Alice  25.0      F  50000.0         HR
1      Bob  30.0      M  60000.0    Finance
2  Charlie   NaN      M  55000.0         IT
3    David  40.0      M  58000.0         HR
4      Eve  22.0      F  52000.0         IT

In [14]:
df.tail()

    Name    Age Gender   Salary Department
5  Frank   35.0    NaN  61000.0    Finance
6  Grace  120.0      F      NaN    Finance
7  Henry   28.0      M  59000.0         HR
8    Ivy   29.0      F  63000.0         IT
9   Jack   27.0      M  62000.0    Finance

In [15]:
from sklearn.preprocessing import OneHotEncoder
one=OneHotEncoder(sparse_output=False)
df['Gender']=one.fit_transform(df[['Gender']])
df

      Name    Age  Gender   Salary Department
0    Alice   25.0     1.0  50000.0         HR
1      Bob   30.0     0.0  60000.0    Finance
2  Charlie    NaN     0.0  55000.0         IT
3    David   40.0     0.0  58000.0         HR
4      Eve   22.0     1.0  52000.0         IT
5    Frank   35.0     0.0  61000.0    Finance
6    Grace  120.0     1.0      NaN    Finance
7    Henry   28.0     0.0  59000.0         HR
8      Ivy   29.0     1.0  63000.0         IT
9     Jack   27.0     0.0  62000.0    Finance

In [18]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Gender']=le.fit_transform(df[['Gender']])
df

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

      Name    Age  Gender   Salary  Department_HR  Department_IT
0    Alice   25.0       1  50000.0           True          False
1      Bob   30.0       0  60000.0          False          False
2  Charlie    NaN       0  55000.0          False           True
3    David   40.0       0  58000.0           True          False
4      Eve   22.0       1  52000.0          False           True
5    Frank   35.0       0  61000.0          False          False
6    Grace  120.0       1      NaN          False          False
7    Henry   28.0       0  59000.0           True          False
8      Ivy   29.0       1  63000.0          False           True
9     Jack   27.0       0  62000.0          False          False

In [17]:
df=pd.get_dummies(df,columns=['Department'],drop_first=True)
df

      Name    Age  Gender   Salary  Department_HR  Department_IT
0    Alice   25.0       1  50000.0           True          False
1      Bob   30.0       0  60000.0          False          False
2  Charlie    NaN       0  55000.0          False           True
3    David   40.0       0  58000.0           True          False
4      Eve   22.0       1  52000.0          False           True
5    Frank   35.0       0  61000.0          False          False
6    Grace  120.0       1      NaN          False          False
7    Henry   28.0       0  59000.0           True          False
8      Ivy   29.0       1  63000.0          False           True
9     Jack   27.0       0  62000.0          False          False